# Setting up a Python environment and pre-commit.

# Unix or MacOS:
# >>> python3 -m venv venv
# >>> source venv/bin/activate

# Windows:
# >>> python -m venv venv
# >>> venv\Scripts\activate.bat

# >>> pip install --upgrade pip
# >>> pip install pre-commit
# >>> pre-commit install
# >>> pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/realm/SwiftLint
    rev: 0.62.2
    hooks:
      - id: swiftlint
        name: run swiftlint linting check
        entry: swiftlint --strict

  - repo: https://github.com/to-sta/spdx-checker-pre-commit
    rev: 0.1.3
    hooks:
      - id: spdx-license-checker
        name: run spdx-checker license check
        args: [-l, GPL-3.0-or-later]
        types_or: [swift]
