name: pr_maintainer_checklist
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  add_pr_checklist:
    runs-on: ubuntu-latest
    name: Add PR Maintainer Checklist
    permissions:
      pull-requests: write
    steps:
      - name: Thank You Message
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Thank you for the pull request! ‚ù§Ô∏è

            The Scribe-iOS team will do our best to address your contribution as soon as we can. If you're not already a member of our [public Matrix community](https://matrix.to/#/#scribe_community:matrix.org), please consider joining! We'd suggest using [Element](https://element.io/) as your Matrix client, and definitely join the `General` and `iOS` rooms once you're in. Also consider attending our [bi-weekly Saturday dev syncs](https://etherpad.wikimedia.org/p/scribe-dev-sync). It'd be great to meet you üòä

      - name: Add Checklist
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Maintainer Checklist

            The following is a checklist for maintainers to make sure this process goes as well as possible. Feel free to address the points below yourself in further commits if you realize that actions are needed :)

            - [ ] The linting and formatting workflows within the [PR checks](https://github.com/scribe-org/Scribe-iOS/pull/${{ github.event.pull_request.number }}/checks) do not indicate new errors in the files changed

            - [ ] The CI unit test workflows within the [PR checks](https://github.com/scribe-org/Scribe-iOS/pull/${{ github.event.pull_request.number }}/checks) do not indicate new errors in the files changed

            - [ ] The [CHANGELOG](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md) has been updated with a description of the changes for the upcoming release and the corresponding issue (if necessary)

      - name: First PR Contributor Email Check
        id: first_interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            ## First PR Commit Check

            - [ ] The commit messages for the remote branch should be checked to make sure the contributor's email is set up correctly so that they receive credit for their contribution
            - The contributor's name and icon in remote commits should be the same as what appears in the PR
            - If there's a mismatch, the contributor needs to make sure that the [email they use for GitHub](https://github.com/settings/emails) matches what they have for `git config user.email` in their local Scribe-iOS repo (can be set with `git config --global user.email "GITHUB_EMAIL"`)
